version: "3"
services:

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432" # use port that you want to in your local instead of 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  api:
    build: ./api
    command: bash -c "rm -f /api/tmp/pids/server.pid && foreman start -f /api/Procfile"
    environment:
      - PORT=3000
    volumes:
      - ./api:/api
      - rails_log:/api/log
    ports:
      - "3000:3000" # use port that you want to in your local instead of 3000
    depends_on:
      - db

volumes:
  db:
  rails_log:
